### ISSUE TITLE
List of holiday names, check if date is specific holiday by name

### ISSUE THREAD

**Issue by AlexZeitler** [sfakir/feiertagejs#1]
Thanks for this useful module.

Here is a feature request:
Generate a list of holiday names and being able to check if a particular date is a holiday by it's name.

**Comment by sfakir** [comment]
Hi Alex,
thanks for your request.
What API would you expect?

Something like this?

feiertagejs.isSpecificHoliday( date, 'Ostersonntag');

feiertagejs.getAllHolidays( 'BW' );
=>
[ object: {name: 'Ostersonntag', date: new Date() }, ... ]

**Comment by AlexZeitler** [comment]
Hi Simon,

if ```feiertagejs.getAllHolidays( 'BW' );``` returns ```[ {name: 'Ostersonntag', date: new Date() }]``` one could already check if a particular day is a holiday but having a convenience method like ```feiertagejs.isSpecificHoliday( date, 'Ostersonntag');``` would be great.

**Comment by sfakir** [comment]
Hi Alex,
ok, i have this on my to do list, but do not expect it within the next 2 weeks. I focus first on code quality and added some tests for the basic functionality.

I you have any more issues, feel free to contribute them.
(btw. please update to 0.1.2)  and in case you are happy, give me a star :+1:  :)

**Comment by sfakir** [comment]
Hi Alex,
I know this request is a bit old, but I had to rewrite major parts of the logic. 

Just released the Version 1.1.0 which includes a getHolidays Method, which returns also the names. Also their is the new 'isSpecificHoliday'-Method. I hope this helps. 

Simon

**Comment by AlexZeitler** [comment]
Hi Simon, no worries. The timing was almost perfect :+1:
