### ISSUE TITLE
Maria Himmelfahrt in Bayern

### ISSUE THREAD

**Issue by thorstenv** [sfakir/feiertagejs#18]
Hi,

bei der Funktion für Maria Himmelfahrt steht region == 'SL' || region == 'ALL'.
Da das nur in Bayern und Saarland ein Feiertag ist müsste wohl statt ALL ein BY hin.

**Comment by sfakir** [comment]
Hi Thorsten,

danke für die Info - wird gleich aktualisiert.

Simon
