### ISSUE TITLE
Add Weltfrauentag in Berlin as Holiday

### ISSUE THREAD

**Issue by mr-bw-dev** [sfakir/feiertagejs#27]
Hey, 
first of all thank you, for that incredibly useful library. It is  a pleasure to us it. 
I would like to ask you to add another holiday to the library. It is Weltfrauentag, on 8th of March and it is a holiday that is only in Berlin. It it will be holiday for the first time this year.  Thank you.

**Comment by sfakir** [comment]
Hello mr-bw-dev,
thank you for the comment. I just added it including some tests in the latest version (1.2.4.)

https://github.com/sfakir/feiertagejs/commit/3b2b2901008ebff13f7ab384862c69c421c53495

Have a good day.

Simon
