### ISSUE TITLE
make isHoliday immutable

### ISSUE THREAD

**Issue by TehEbil** [sfakir/feiertagejs#28]
Hey,

I came across a bug where isHoliday caused an error. It actually changed my time, so I had to pass a copy of my dateObject.

The reason probably is here:
```
function toUtcTimestamp(date: Date): number {
  date.setHours(0, 0, 0, 0);
  return date.getTime();
}
```

Maybe you shouldnt use setHours on the passed date but return a new Date():

```
function toUtcTimestamp(date: Date): number {
  let tmpDate = new Date(date);
  tmpDate.setHours(0,0,0,0);
  return tmpDate.getTime();
}
```

Kind Regards

**Comment by sfakir** [comment]
Hi TehEbil,

thank you for the feedback. Makes totally sense and is fixed in version 1.2.6.

Simon
