### ISSUE TITLE
Public Holiday missing Bavaria

### ISSUE THREAD

**Issue by ThomasPoett** [sfakir/feiertagejs#33]
Hi
the public holiday "Frohnleichnam" Easter Sunday + 60 is missing.
do you mind adding it in?

**Comment by sfakir** [comment]
Hi Thomas,

sorry for the delayed message. Could you provide the parameters you used. Also the package version may help!

I just tried to reproduce this behaviour using the following test, but I receive Frohenleichnam for 2019:

```
 it('find Frohenleichnam in 2019 in BY', () => {
    const FROHENLEICHNAM = new Date(2019, 6 - 1, 20);
    expect(getHolidayByDate(FROHENLEICHNAM, 'BY')).toEqual(
      expect.objectContaining({
        name: 'FRONLEICHNAM',
      }),
    );
  });
```
Thank you

Simon

**Comment by sfakir** [comment]
Hi Thomas,
I closed this issue, becuse the test seemed to work.
