### ISSUE TITLE
bower install feiertagejs not working

### ISSUE THREAD

**Issue by kkoepke** [sfakir/feiertagejs#4]
bower  ENOTFOUND Package feiertagejs not found

npm install is working fine.

**Comment by sfakir** [comment]
Hi kkopeke,
thank you for the feedback. I just registered it again on bower. 

```
bower info feiertagejs
bower feiertagejs#*         not-cached https://github.com/sfakir/feiertagejs.git#*
```

enjoy  👍 
If you have any more feedback let me know.
