### ISSUE TITLE
Please publish a new version

### ISSUE THREAD

**Issue by jannikkeye** [sfakir/feiertagejs#41]
Seems like lots of things have happened and the api changed. Also typescript definitions were added. Would be great to have those things published :) 🚀

**Comment by jannikkeye** [comment]
Seems upgrading wouldn't be possible for us anyway since for example I cannot fetch Feiertage for BY-FF like Augsburger Friedensfest anymore.

**Comment by sfakir** [comment]
Hi Jannik,
thank you for the request, in fact the Typescript update was not meant to be incompatible with the old version, I am going to review it and keep you updated.

**Comment by sfakir** [comment]
1) Region AUGSBURG was added. Which will be supported, however, in the future we might need to separate between main regions and subregions.
Sample: https://github.com/sfakir/feiertagejs/blob/master/spec/localholidays.spec.ts;
2) Released version 1.3.0 which has now full typescript support :+1:

Let me know if anything else is needed.
