### ISSUE TITLE
Compatibility between feiertagejs and DateJs

### ISSUE THREAD

**Issue by safebyte** [sfakir/feiertagejs#5]
When using [DateJs](http://www.datejs.com/) together with feiertagejs, some of the DateJs functions seem to stop working. For example:

    Date.today().add(1).day(); // -> undefined when using with feiertagejs

Is there a way to use both libraries together? Thanks.

**Comment by sfakir** [comment]
Hello safebyte,
sorry for the delay! I just released 1.1.5 which fixed compatibility issues with other packages. In case you have the setup still running you might test it and give feedback.

Thank you

Simon
