### ISSUE TITLE
Holiday 'Frauentag' is missing 'Mecklenburg-Vorpommern' state

### ISSUE THREAD

**Issue by AvgustPol** [sfakir/feiertagejs#56]
# Issue: 
Holiday 'Frauentag' (eng. women's day) is missing 'Mecklenburg-Vorpommern' state 

**Hint:** in Holidays[] array it called 'WELTFRAUENTAG'

# Description: 
Checked your implementation and looks like one more state for holiday 'Frauentag' is missing 

![image](https://user-images.githubusercontent.com/29002229/203819355-e78615de-09c2-4155-b33b-e7a9fb0c9d3e.png)

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland 
![image](https://user-images.githubusercontent.com/29002229/203820536-74e7dd3c-b87a-41ca-a4ef-5c1a3d921e13.png)

**Comment by sfakir** [comment]
fixed.
