### ISSUE TITLE
Holiday 'Reformationstag' is missing 'Schleswig-Holstein' state 

### ISSUE THREAD

**Issue by AvgustPol** [sfakir/feiertagejs#57]
# Issue: 
Holiday 'Reformationstag' is missing 'Schleswig-Holstein' state 

**Hint:** in Holidays[] array it called 'REFORMATIONSTAG'

# Description: 
Checked your implementation and looks like one more state for holiday 'Frauentag' is missing 

![image](https://user-images.githubusercontent.com/29002229/203833995-09a908f8-9e90-4743-9292-52e9c802fca6.png)

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland 
![image](https://user-images.githubusercontent.com/29002229/203833765-87b43ec6-f259-46f8-b632-4698b9092126.png)

**Comment by sfakir** [comment]
Thank you, here I could find an official source, that it [became a holiday in 2018]. I will add it. (https://www.landtag.ltsh.de/nachrichten/18_02_feiertag/#:~:text=Der%20Reformationstag%20wird%20gesetzlicher%20Feiertag,Oktober%2C%20schul%2D%20und%20arbeitsfrei.&text=Der%20Reformationstag%20wird%20gesetzlicher%20Feiertag%20in%20Schleswig%2DHolstein.,-Das%20hat%20der).
