### ISSUE TITLE
Holiday 'Ostersonntag' is missing 'Hessen' state

### ISSUE THREAD

**Issue by AvgustPol** [sfakir/feiertagejs#58]
# Issue: 
Holiday 'Ostersonntag' is missing 'Hessen' state 

**Hint:** in Holidays[] array it called 'OSTERSONNTAG'

# Description: 
Checked your implementation and looks like one more state for holiday 'Ostersonntag' is missing 

![image](https://user-images.githubusercontent.com/29002229/203834994-1e065262-d3c2-4a7c-bec9-7fc0eceb0fab.png)

https://de.wikipedia.org/wiki/Gesetzliche_Feiertage_in_Deutschland 
![image](https://user-images.githubusercontent.com/29002229/203834881-12be3bd7-cfa9-4b0e-a922-5ba56c373091.png)

**Comment by sfakir** [comment]
Same issue as #59
