### ISSUE TITLE
Buß- und Bettag dosent match

### ISSUE THREAD

**Issue by juergenTrings** [sfakir/feiertagejs#6]
Every date matches, but the Buß- und Bettag is wrong...

`date:Wed Oct 04 2017 00:00:00 GMT+0200 (CEST)
name:"BUBETAG"`

tried it with different years but it is always wrong. 
(Buß- und Bettag is only in Saxony!)

**Comment by sfakir** [comment]
Hi,
I found that there was an mistake in its calculation. I just replaced it and added unit test. Please find v1.1.5 ready on bower/npm right now.
Best,
Simon

**Comment by juergenTrings** [comment]
Hey ich hatte selbst einen Fix geschrieben und einen Commit gemacht. Wollte bloß wissen ob du den gesehen hast (bin neu auf Github und habe das noch nicht so häufig gemacht) 

Von meinem iPhone gesendet
