### ISSUE TITLE
Attempted import error

### ISSUE THREAD

**Issue by fjw** [sfakir/feiertagejs#64]
on react/next.js with typescript I run into this error on version 1.3.6:

`Attempted import error: 'isHoliday' is not exported from 'feiertagejs' (imported as 'isHoliday').`

when importing like this:

`import { isHoliday } from "feiertagejs";`

isHoliday is then undefined.

a rollback to 1.3.5 solved the issue for me

**Comment by johannschopplich** [comment]
Same error for here.

```bash
__vite_ssr_import_2__.getHolidays is not a function
```
