### ISSUE TITLE
NPM package is missing region 'AUGSBURG' in the typescript types

### ISSUE THREAD

**Issue by Whinny3873** [sfakir/feiertagejs#65]
In the npm package the region 'AUGSBURG' is missing from the index.d.ts types.
![image](https://user-images.githubusercontent.com/113519408/231130511-082f6f66-76f5-43d4-88eb-f37a0edb272d.png)
So the typescript transpiler will throw an error when trying to use AUGSBURG as region.

Workaround: Cast 'AUGSBURG' to Region:
```typescript
isSunOrHoliday(myDate, 'AUGSBURG' as Region)
```

**Comment by sfakir** [comment]
@Whinny3873 ,
thank you for the comment.
Fixed in 1.3.9 (typing file was missing Augsburg)

Simon
